spring:
 application:
  name: product-service
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service
logging:
  level:
    root: off
    com.whitecode: DEBUG
server:
  port: 9788
---
spring:
  config:
    activate:
      on-profile: localhost
  datasource:
    url: jdbc:postgresql://postgres:5432/stock_management
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    platform: postgres
  profiles:
    active: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: stock_management
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
---
spring:
  config:
    activate:
      on-profile: stage
  datasource:
    url: jdbc:postgresql://postgres:5432/stock_management
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    platform: postgres
  profiles:
    active: stage
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: stock_management
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}




